### ISSUE TITLE
Array Field is still not properly supported in latest version(0.3.1)

### ISSUE THREAD

**Issue by JunHyunJunHyun** [Brobin/django-seed#106]
Connected issue.
https://github.com/Brobin/django-seed/issues/104

We are using the latest version, but Array Field is still not properly supported.

```
pip list

django-seed 0.3.1
```

No matter what form the model is modified, Array Field is not properly recognized.

```
models.py

1. blablaField = ArrayField(models.TextField(), blank=False, size=6, null=True)
 
2. blablaField = ArrayField(
        models.TextField(),
        blank=True,
        size=6,
        null=True,
    )

3. blablaField = ArrayField(
        models.TextField(
            max_length=100,
            null=True,
        ),
        blank=True,
        size=6,
        null=True,
    )

4. blablaField = ArrayField(
        models.TextField(
            max_length=100,
            null=True,
            blank=True,
        ),
        blank=True,
        size=6,
        null=True,
    )
```

When I deleted the field only right, it worked.

```
models.py

~~~

(delete blablaField)

~~~
```

I think an error occurs when the model is verified in the add_entity process. This is because an error occurred even if a field value was not added within add_entity.

```
seed_blablas.py

class Command:

~~

def handle(self, *args, **options):
        total = options.get("total")
        seeder = Seed.seeder()
        seeder.add_entity(

=========== here ===============

            blablaModels, 

=========== here ===============

            total,
            {
                "name": lambda x: "name" + seeder.faker.first_name(),
                "code": lambda x: "code" + seeder.faker.first_name(),
            },
        )
       seeder.execute()
```

```
Error

Creating server_django_run ... done
PostgreSQL is available
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/app/server/blablaModels/management/commands/seed_blablas.py", line 16, in handle
    seeder.add_entity(
  File "/usr/local/lib/python3.8/site-packages/django_seed/seeder.py", line 132, in add_entity
    model.field_formatters = model.guess_field_formatters(self.faker)
  File "/usr/local/lib/python3.8/site-packages/django_seed/seeder.py", line 60, in guess_field_formatters
    formatter = field_type_guesser.guess_format(field)
  File "/usr/local/lib/python3.8/site-packages/django_seed/guessers.py", line 109, in guess_format
    raise AttributeError(field)
AttributeError: blabla.blablaModels.blablaField
```

Since it is an internal code of the company, it has been modified to blabla. Let me know if there's another problem!

**Comment by JunHyunJunHyun** [comment]
It was solved. It was because of the docker environmental problem. I'll close the issue.
