### ISSUE TITLE
Field auth.Permission.codename cannot be null

### ISSUE THREAD

**Issue by paulshannon** [Brobin/django-seed#11]
`manage.py seed auth` results in:

	(venv)vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python manage.py seed auth
	Seeding 10 Permissions
	Seeding 10 Groups
	Seeding 10 Users
	Traceback (most recent call last):
	  File "manage.py", line 10, in <module>
		execute_from_command_line(sys.argv)
	  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
		utility.execute()
	  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
		self.fetch_command(subcommand).run_from_argv(self.argv)
	  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
		self.execute(*args, **options.__dict__)
	  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
		output = self.handle(*args, **options)
	  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 449, in handle
		app_output = self.handle_app_config(app_config, **options)
	  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_seed/management/commands/seed.py", line 38, in handle_app_config
		pks = seeder.execute()
	  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_seed/seeder.py", line 133, in execute
		entity = self.entities[klass].execute(using, inserted_entities)
	  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_seed/seeder.py", line 71, in execute
		setattr(obj, field, format(inserted_entities))
	  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_seed/seeder.py", line 39, in build_relation
		raise SeederException(message)
	django_seed.exceptions.SeederException: Field auth.Permission.codename cannot be null
	(venv)vagrant@vagrant-ubuntu-trusty-64:/vagrant$

django 1.7.8
django_seed from git

**Comment by Brobin** [comment]
This is a foreign key constraint issue that I still haven't come up with a good solution for. Similar to issue #8. Ideally, I would like to add some logic to sort the models based on dependencies so that we never run into this issue. If you have some ideas on how to accomplish this, I'd love some help :)

In the meantime, I'd recommend seeding with the code version (ie: `seeder.add_entity(Model, 10)` in an order based on their dependencies to avoid this conflict

**Comment by Brobin** [comment]
Resolved in #26
