### ISSUE TITLE
Issues with max_length

### ISSUE THREAD

**Issue by cdvv7788** [Brobin/django-seed#40]
DataError: value too long for type character varying(50)

Seeding should take into account the max_length of the field.

**Comment by Brobin** [comment]
Is the max_length of the problem field less than 5? If so, I think I know what the problem is and have a quick fix

**Comment by cdvv7788** [comment]
max_length is 50, but the package is generating strings larger than that. I am not familiar with the package code, but i think that a slice should be enough to fix it.

**Comment by Brobin** [comment]
And it is a CharField? I'm passing the max_length to the provider for that https://github.com/Brobin/django-seed/blob/master/django_seed/guessers.py#L100

**Comment by cdvv7788** [comment]
Yes. It is a charfield. It happens at random but with more tests it is happening more often now.

**Comment by Brobin** [comment]
That's very interesting. I wonder if it's hitting a field guesser instead of the regular provider. Here's the flow

1. Check if the field has a known name (first_name, last_name, username) etc. and give it a value that makes sends
2. If not, call  `faker.text(field.max_length)` which should give lorem ipsum text.

It's either getting identified as something special at step 1, or the faker package is messing up at step 2. What's the field called?

**Comment by cdvv7788** [comment]
I am not sure which field is failing.
The whole stacktrace is:
```
Traceback (most recent call last):
File "/home/rof/src/github.com/swappsco/accountant/accountant/payment_orders/tests.py", line 65, in setUp
self.pks = seeder.execute()
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django_seed/seeder.py", line 143, in execute
entity = self.entities[klass].execute(using, inserted_entities)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django_seed/seeder.py", line 86, in execute
for field, field_format in self.field_formatters.items()
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 399, in create
obj.save(force_insert=True, using=self.db)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
force_update=force_update, update_fields=update_fields)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
using=using, raw=raw)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
return query.get_compiler(using=using).execute_sql(return_id)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
cursor.execute(sql, params)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
return self.cursor.execute(sql, params)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
return self.cursor.execute(sql, params)
DataError: value too long for type character varying(50)
```
In my model i have only 2 fields with max_length=50: tax_name and resolution_number. I doubt those are used for special cases.

**Comment by TitanFighter** [comment]
If someone else has this problem, it can be solved like this (In the example I use model `User` and field `username`:

```
from django_seed import Seed
from .models import User

def seed_user():
    seeder = Seed.seeder()

    seed_data = dict(
        username=lambda x: seeder.faker.user_name()[:User._meta.get_field('username').max_length],
    )

    seeder.add_entity(User, 25, seed_data)
    inserted_pks = seeder.execute()

```
