### ISSUE TITLE
Field 'id' expected a number but got a dict

### ISSUE THREAD

**Issue by brunowego** [Brobin/django-seed#89]
First time using Django Seed. Great project, congrats! I'm trying understand this issue:

```sh
$ ./manage.py seed_responses --number 15
Traceback (most recent call last):
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/src/secret/api/core/management/commands/seed_responses.py", line 36, in handle
    seeder.execute()
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django_seed/seeder.py", line 157, in execute
    entity = self.entities[klass].execute(using, inserted_entities)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django_seed/seeder.py", line 101, in execute
    obj = manager.create(**faker_data)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1339, in as_sql
    value_rows = [
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1340, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1340, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1281, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/fields/related.py", line 971, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 823, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2388, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/src/secret/api/.venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got {<class 'core.models.Response'>: []}.
```

Can help me? My model:

```py
from django.core.management import BaseCommand
from django_seed import Seed
from core.models import Application, Campaign, Response
# import uuid
import random
from django.contrib.auth import get_user_model


class Command(BaseCommand):
    help = 'This command creates many responses.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--number', default=1, help='How many responses do you want to create?'
        )

    def handle(self, *args, **options):
        number = int(options.get('number', 1))
        seeder = Seed.seeder()
        applications = Application.objects.all()
        campaigns = Campaign.objects.all()

        seeder.add_entity(Response, number, {
            # 'id': lambda x: uuid.uuid4(),
            'completed': False,
            'application': lambda x: random.choice(applications),
            'userId': 1,
            'campaign': lambda x: random.choice(campaigns),
            'deleted_by': get_user_model(),
        })
        seeder.execute()

        self.stdout.write(self.style.SUCCESS('{} responses created.'.format(number)))
```

```txt
Django==3.1.1
psycopg2-binary==2.8.6
djangorestframework==3.11.1
django-cors-headers==3.5.0
django-extensions==3.0.9
django-colorfield==0.3.2
django-environ==0.4.5
django-q==1.3.3
django-seed==0.2.2
uWSGI==2.0.19.1
django-extensions==3.0.9
uWSGI==2.0.19.1
python-ulid==1.0.2
sentry-sdk==0.19.4
redis==3.5.3
whitenoise==5.2.0
```

**Comment by brunowego** [comment]
It just worked after lunch. @@

**Comment by AngelOnFira** [comment]
I'll still take a look over it in case there is something we can handle better. Thanks :smiley:

**Comment by brunowego** [comment]
Thanks @AngelOnFira  for your attention!
